__author__ = 'jc449735'
temp_file=open("temp.txt","w")
print("first line ",file=temp_file)
print("second line ",file=temp_file)
print("third line ",file=temp_file)
print("fourth line ",file=temp_file)
print("this is the beggining of new kind of pain ",file=temp_file)
temp_file.close()
print("==")
temp_file = open("temp.txt","r")
for line in temp_file:
    line=line.strip()
    print(line)
temp_file.close()
print("==")
temp_file=open("temp.txt","r")
mystring=temp_file.read()
print(mystring)
temp_file.close()

print("==")
temp_file=open("temp.txt","r")
#mystrings=temp_file.readlines()
#print(mystring)
for line in temp_file:
    line=line.strip()
    print(line)
temp_file.close()
print("==")
my_list=("fl\n","sl\n","tl\n","4l\n")
out_file=open("out.txt","w")
out_file.writelines(my_list)
out_file.close()

